  - alias: 'Auto Renew SSL Cert'
    trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 29
    action:
      service: shell_command.renew_ssl

  - alias: 'SSL expiry notification'
    trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 21
    action:
      service: notify.notify
      data:
        message: 'Warning - SSL certificate expires in 21 days and has not been automatically renewed'

  - alias: Basement Entry Light On
    trigger:
      platform: state
      entity_id: input_boolean.sengled_basemententry
      from: 'off'
      to: 'on'
    action:
      service: ifttt.trigger
      data: {"event":"sengled_basentry"}
 
  - alias: Basement Entry Light Off
    trigger:
      platform: state
      entity_id: input_boolean.sengled_basemententry
      from: 'on'
      to: 'off'
    action:
      service: ifttt.trigger
      data: {"event":"sengled_basentry"}

########################################
#   WASHER/TPLINK HS110 NOTIFICATION   #
#            30 DEC 2018               #
########################################

# Washer switch state on
#  - id: washer_on
  - alias: Washing Machine On
    trigger:
      entity_id: sensor.washer_amps
      platform: numeric_state
      above: '3.4'
      for:
        minutes: 1
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.washer_switch  

# Washer switch state off
#  - id: washer_done_switch_state
  - alias: Washing Machine Done
    trigger:
      entity_id: sensor.washer_amps
      platform: numeric_state
      below: '3.4'  
    condition:
      condition: state
      entity_id: 'input_boolean.washer_switch'
      state: 'on'  
    action:
      service: input_boolean.turn_off
      entity_id: input_boolean.washer_switch
    
# Washer Done anouncement
#  - id: washer_done
  - alias: Washing Machine Done
    trigger:
      entity_id: input_boolean.washer_switch 
      platform: state
      to: 'off'
    condition:
      condition: time
      after: '8:00:00'
      before: '23:00:00'
    action:
      service: notify.ios_brian_iphone
#     entity_id: media_player.hallway_speaker
      data: {"message": "The Washing Machine is Finished","cache":"true"}

